nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-berry.cjs

plugins:
    - ./packages/version-inject/bundles/@yarnpkg/plugin-version-inject.js

sharedVersions:
    yarn-version: ^3.1.0
